# -*- coding: utf-8 -*-
"""BA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12HQUicwnxef8CeggPFK--muf1Xc_gyZw
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv("avocado.csv")
df = pd.DataFrame(data)
df.head()

data.info()
data.describe()

data.columns

data.isnull().sum()

data.columns

df['Date']=pd.to_datetime(df['Date'])
df['Year']=df['Date'].dt.year
df['Month']=df['Date'].dt.month
df=df.dropna()

df

from sklearn.preprocessing import LabelEncoder

label=LabelEncoder()
df['type']=label.fit_transform(df['type'])
df['region']=label.fit_transform(df['region'])

x=df[['Total Volume','4046','4225','4770','type','Year','Month','region' ]]
y=df['AveragePrice']

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
model=LinearRegression()
model.fit(x_train,y_train)

y_pred=model.predict(x_test)
mse=mean_squared_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)
print("Mean Squared Error:",mse)
print("R-squared:",r2)

import matplotlib.pyplot as plt
plt.scatter(y_test,y_pred,alpha=0.6)
plt.xlabel("Actual  Price")
plt.ylabel("Predicted  Price")
plt.title("Actual vs Predicted  Prices")
plt.show()

importance=pd.DataFrame({'Features':x.columns,'Coefficients':model.coef_})
importance=importance.sort_values(by='Coefficients',ascending=False)
importance

plt.figure(figsize=(8,5))
plt.barh(importance['Features'],importance['Coefficients'])
plt.xlabel('Coefficients')
plt.title('Feature Importance')
plt.show()

import joblib
joblib.dump(model,'avocado_model.pkl')

